apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scooldUploads
  name: scooldUploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
