apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: scoold
  name: scoold
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scoold
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: scoold
    spec:
      containers:
        - env:
            - name: BOOT_SLEEP
              value: "5"
            - name: JAVA_OPTS
              value: "-Dconfig.file=/config/application.conf -Dscoold.port=8000 -Dscoold.para_endpoint=http://para:8080"
          image: erudikaltd/scoold:latest
          name: scoold
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /scoold/uploads
              name: scoolduploads
            - mountPath: /scoold/application.conf
              name: scoold-claim1
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: scoolduploads
          persistentVolumeClaim:
            claimName: scoold-uploads
        - name: scoold-claim1
          persistentVolumeClaim:
            claimName: scoold-claim1
        - name: config
          secret:
            secretName: scoold-config
        