apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: scoold-ukubeploads
  name: scoold-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
