---
apiVersion: v1
kind: Secret
metadata:
  name: para-config
type: Opaque
data:
{{ (.Files.Glob "conf/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: para-env
type: Opaque
stringData:
  PARA_ACCESS_KEY: "app:para"
  PARA_SECRET_KEY: "AP86NKVd8KL0S6mRfpim/58QOyLSxEUtwlZXGhvBcFxL9oNewDCfnQ=="
  PARA_ENDPOINT: "http://localhost:8080"