apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: paralib
  name: paralib
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
