apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: paradata
  name: paradata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
