apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: para
  name: para
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: para
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: para
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: "-Dconfig.file=/config/application.conf -Dloader.path=/para/lib -Dpara.port=8080"
          image: erudikaltd/para:latest_stable
          name: para
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /para/data
              name: paradata
            - mountPath: /para/lib
              name: paralib
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: paradata
          persistentVolumeClaim:
            claimName: paradata
        - name: paralib
          persistentVolumeClaim:
            claimName: paralib
        - name: config
          secret:
            secretName: para-config
            defaultMode: 0700