apiVersion: v2
name: db2rest
home: https://db2rest.com
sources:
  - https://db2rest.com
  - https://github.com/kdhrubo/db2rest
description: A Helm chart for db2rest, a universal and ready-to-use REST read/write API for any SQL database
type: application
version: 0.2.0
appVersion: "1.16.0"
keywords:
  - database
  - sql
  - rest
  - api
  - openapi
maintainers:
  - name: Ludger Pottmeier
    email: ludger.pottmeier@gmail.com
annotations:
  licenses: Apache-2.0
  artifacthub.io/category: database
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Ludger Pottmeier
      email: ludger.pottmeier@gmail.com
  artifacthub.io/links: |
    - name: db2rest
      url: https://db2rest.com
    - name: Documentation
      url: https://db2rest.com/docs
    - name: Support
      url: https://github.com/hurzelpurzel/helmcharts/issues
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of the db2rest Helm chart
    - kind: changed
      description: Add metadata for Artifact Hub publication
