name: ci-helm-ghcr
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: azure/setup-helm@v5
        with:
          version: latest

      - name: Helm lint all charts
        run: |
          for chart in */Chart.yaml; do
            helm lint "$(dirname "$chart")"
          done

      - name: Helm login (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Helm package all charts
        run: |
          for chart in */Chart.yaml; do
            helm package "$(dirname "$chart")"
          done

      - name: Helm push to GHCR
        if: github.event_name == 'push'
        run: |
          for pkg in *.tgz; do
            helm push "$pkg" "oci://ghcr.io/${{ github.repository_owner }}"
          done
